"""empty message

Revision ID: a0028aa01688
Revises: b3b40fbcf2a0
Create Date: 2024-02-18 15:56:01.785238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0028aa01688'
down_revision: Union[str, None] = 'b3b40fbcf2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'member', ['mail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='unique')
    op.create_table('association_table',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], name='association_table_company_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='association_table_user_id_fkey')
    )
    # ### end Alembic commands ###
