"""empty message

Revision ID: 6049000bb7e4
Revises: 06ae5121cbec
Create Date: 2024-03-22 23:20:09.858919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6049000bb7e4'
down_revision: Union[str, None] = '06ae5121cbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('option_question_id_fkey', 'option', type_='foreignkey')
    op.create_foreign_key(None, 'option', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('question_quiz_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'quiz', ['quiz_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_quiz_id_fkey', 'question', 'quiz', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_foreign_key('option_question_id_fkey', 'option', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
