"""empty message

Revision ID: 2d8e5b3a87b7
Revises: 018584e27a3a
Create Date: 2024-03-03 12:50:31.646629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8e5b3a87b7'
down_revision: Union[str, None] = '018584e27a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['member.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('admin')
    # ### end Alembic commands ###
