"""empty message

Revision ID: 8a505e72c0eb
Revises: 73dc40f5b613
Create Date: 2024-02-10 19:40:31.618212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a505e72c0eb'
down_revision: Union[str, None] = '73dc40f5b613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('company', 'company_id')
    op.drop_constraint('request_company_id_fkey', 'request', type_='foreignkey')
    op.create_foreign_key(None, 'request', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.create_foreign_key('request_company_id_fkey', 'request', 'company', ['company_id'], ['company_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('company', sa.Column('company_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('company', 'id')
    # ### end Alembic commands ###
