"""empty message

Revision ID: 018584e27a3a
Revises: a0028aa01688
Create Date: 2024-02-21 17:53:17.004996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018584e27a3a'
down_revision: Union[str, None] = 'b3b40fbcf2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'company_name')
    op.drop_column('member', 'name')
    op.drop_column('request', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
