"""empty message

Revision ID: e3d03d92d50a
Revises: 765104a3c280
Create Date: 2024-02-08 16:14:30.808535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d03d92d50a'
down_revision: Union[str, None] = '765104a3c280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_owner_id_fkey', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'user', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key('company_owner_id_fkey', 'company', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
